# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build and push docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build images
      run: docker compose build
      env:
        ASPNETCORE_ENVIRONMENT: ${{ secrets.ASPNETCORE_ENVIRONMENT }}
        ASPNETCORE_HTTP_PORTS: ${{ secrets.ASPNETCORE_HTTP_PORTS }}
        ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTIONSTRINGS__DEFAULTCONNECTION }}
        Jwt__Key: ${{ secrets.JWT__KEY }}
        Jwt__Issuer: ${{ secrets.JWT__ISSUER }}
        Jwt__Audience: ${{ secrets.JWT__AUDIENCE }}
        Jwt__ExpiryInMinutes: ${{ secrets.JWT__EXPIRYINMINUTES }}
        MailSettings__Email: ${{ secrets.MAILSETTINGS__EMAIL }}
        MailSettings__DisplayName: ${{ secrets.MAILSETTINGS__DISPLAYNAME }}
        MailSettings__Password: ${{ secrets.MAILSETTINGS__PASSWORD }}
        MailSettings__Host: ${{ secrets.MAILSETTINGS__HOST }}
        MailSettings__Port: ${{ secrets.MAILSETTINGS__PORT }}
        AdminUser__Email: ${{ secrets.ADMINUSER__EMAIL }}
        AdminUser__UserName: ${{ secrets.ADMINUSER__USERNAME }}
        AdminUser__Password: ${{ secrets.ADMINUSER__PASSWORD }}
        LawyerUser__Email: ${{ secrets.LAWYERUSER__EMAIL }}
        LawyerUser__UserName: ${{ secrets.LAWYERUSER__USERNAME }}
        LawyerUser__Password: ${{ secrets.LAWYERUSER__PASSWORD }}
        SuperAdminUser__Email: ${{ secrets.SUPERADMINUSER__EMAIL }}
        SuperAdminUser__UserName: ${{ secrets.SUPERADMINUSER__USERNAME }}
        SuperAdminUser__Password: ${{ secrets.SUPERADMINUSER__PASSWORD }}
        CloudinarySettings__CloudName: ${{ secrets.CLOUDINARYSETTINGS__CLOUDNAME }}
        CloudinarySettings__ApiKey: ${{ secrets.CLOUDINARYSETTINGS__APIKEY }}
        CloudinarySettings__ApiSecret: ${{ secrets.CLOUDINARYSETTINGS__APISECRET }}
        SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
        ACCEPT_EULA: ${{ secrets.ACCEPT_EULA }}

    # - name: Tag image
    #   run: docker tag wakiliy.api ${{ secrets.DOCKER_USERNAME }}/wakiliy.api:latest

    - name: Push Docker image
      run: docker compose push